# packages/rots/src/rots/sidecar/handlers_provision.py

"""SOCKS proxy SSH key provisioning between DB and web instances.

The DB instance has no public IP address and relies on an SSH SOCKS tunnel
through the web server (jumphost) for all outbound connectivity. During
cloud-init, the DB generates an SSH keypair at:

    /etc/socks-proxy/.ssh/id_ed25519

The corresponding public key must be installed into the web server's
authorized_keys so the SOCKS proxy service can establish the tunnel:

    /home/socks-proxy/.ssh/authorized_keys

Provisioning flow:
    1. DB instance generates an ed25519 keypair during cloud-init
    2. Sidecar on DB reads the public key  (provision.socks_key_read)
    3. Sidecar on web writes it to authorized_keys (provision.socks_key_write)
    4. The socks-proxy systemd service can now connect

Commands:
    provision.socks_key_read   — Read the DB's public key from disk and return
                                 it along with the host_id for verification.
    provision.socks_key_write  — Accept a public key string and append it to
                                 the web server's authorized_keys file, ensuring
                                 correct ownership, permissions, and no duplicates.

The ``rots sidecar provision-socks`` CLI command orchestrates both steps,
sending the read command to the DB and the write command to the web server
over the private network via RabbitMQ.
"""

from __future__ import annotations

import logging
import os
import shutil
import stat
from pathlib import Path
from typing import Any

from .commands import Command, CommandResult, register_handler
from .rabbitmq import get_host_id

logger = logging.getLogger(__name__)

# Paths
DB_PUBKEY_PATH = Path("/etc/socks-proxy/.ssh/id_ed25519.pub")
WEB_SSH_DIR = Path("/home/socks-proxy/.ssh")
WEB_AUTHORIZED_KEYS = WEB_SSH_DIR / "authorized_keys"

# Ownership
SOCKS_USER = "socks-proxy"
SOCKS_GROUP = "socks-proxy"


@register_handler(Command.PROVISION_SOCKS_KEY_READ)
def handle_socks_key_read(params: dict[str, Any]) -> CommandResult:
    """Read the SOCKS proxy public key from the DB instance.

    Returns the contents of /etc/socks-proxy/.ssh/id_ed25519.pub
    along with the host_id so the caller can verify which host
    responded.

    Fails gracefully if the key file does not yet exist (the keypair
    may not have been generated by cloud-init yet).
    """
    host_id = get_host_id()

    if not DB_PUBKEY_PATH.exists():
        return CommandResult.fail(
            f"Public key not found at {DB_PUBKEY_PATH} — keypair may not have been generated yet"
        )

    try:
        public_key = DB_PUBKEY_PATH.read_text().strip()
    except OSError as e:
        return CommandResult.fail(f"Failed to read {DB_PUBKEY_PATH}: {e}")

    if not public_key:
        return CommandResult.fail(f"Public key file {DB_PUBKEY_PATH} is empty")

    logger.info(
        "Read SOCKS proxy public key from %s on host_id=%s",
        DB_PUBKEY_PATH,
        host_id,
    )

    return CommandResult.ok(
        {
            "host_id": host_id,
            "public_key": public_key,
            "path": str(DB_PUBKEY_PATH),
        }
    )


@register_handler(Command.PROVISION_SOCKS_KEY_WRITE)
def handle_socks_key_write(params: dict[str, Any]) -> CommandResult:
    """Write a SOCKS proxy public key to the web server's authorized_keys.

    Params:
        public_key (required): SSH public key string to install.

    Ensures:
        - /home/socks-proxy/.ssh exists with mode 0700
        - authorized_keys has mode 0600
        - Ownership is socks-proxy:socks-proxy
        - The key is not duplicated if already present
    """
    host_id = get_host_id()

    public_key = params.get("public_key", "").strip()
    if not public_key:
        return CommandResult.fail("Missing or empty 'public_key' parameter")

    if not public_key.startswith("ssh-"):
        return CommandResult.fail(
            f"Invalid SSH public key: expected key starting with 'ssh-', got '{public_key[:20]}...'"
        )

    # Ensure .ssh directory exists with correct permissions
    try:
        WEB_SSH_DIR.mkdir(parents=True, exist_ok=True)
        os.chmod(WEB_SSH_DIR, stat.S_IRWXU)  # 0700
        shutil.chown(WEB_SSH_DIR, user=SOCKS_USER, group=SOCKS_GROUP)
    except OSError as e:
        return CommandResult.fail(f"Failed to create/configure {WEB_SSH_DIR}: {e}")

    # Check for duplicate key
    if WEB_AUTHORIZED_KEYS.exists():
        try:
            existing_content = WEB_AUTHORIZED_KEYS.read_text()
            existing_keys = {line.strip() for line in existing_content.splitlines() if line.strip()}
            if public_key in existing_keys:
                logger.info(
                    "SOCKS proxy public key already present in %s on host_id=%s",
                    WEB_AUTHORIZED_KEYS,
                    host_id,
                )
                return CommandResult.ok(
                    {
                        "host_id": host_id,
                        "message": "Public key already present in authorized_keys",
                        "path": str(WEB_AUTHORIZED_KEYS),
                        "already_present": True,
                    }
                )
        except OSError as e:
            return CommandResult.fail(f"Failed to read {WEB_AUTHORIZED_KEYS}: {e}")

    # Append public key
    try:
        with WEB_AUTHORIZED_KEYS.open("a") as f:
            # Ensure we start on a new line
            if WEB_AUTHORIZED_KEYS.stat().st_size > 0:
                f.write("\n")
            f.write(public_key + "\n")
    except OSError as e:
        return CommandResult.fail(f"Failed to write to {WEB_AUTHORIZED_KEYS}: {e}")

    # Set permissions and ownership on authorized_keys
    try:
        os.chmod(WEB_AUTHORIZED_KEYS, stat.S_IRUSR | stat.S_IWUSR)  # 0600
        shutil.chown(WEB_AUTHORIZED_KEYS, user=SOCKS_USER, group=SOCKS_GROUP)
    except OSError as e:
        return CommandResult.fail(
            f"Key written but failed to set permissions on {WEB_AUTHORIZED_KEYS}: {e}"
        )

    logger.info(
        "Wrote SOCKS proxy public key to %s on host_id=%s",
        WEB_AUTHORIZED_KEYS,
        host_id,
    )

    return CommandResult.ok(
        {
            "host_id": host_id,
            "message": "Public key written to authorized_keys",
            "path": str(WEB_AUTHORIZED_KEYS),
            "already_present": False,
        }
    )
